### PR TITLE
Update airtime.po

### PR DESCRIPTION
**Pull request by ghost**
finished :)

### CODE REVIEW

**Comment by danielhjames** [comment]
Thanks Magyar, I checked the file formatting and it all looks good!

**Comment by ghost** [comment]
I feel honored. I would like to translate Serbian and Croatian languages. I would like in Serbia and in Hungary create the Source Fabric company. I have companys in Hungary and in Serbia. Who do I talk about?

**Comment by danielhjames** [comment]
More translations would be very welcome :-) I have asked Lisa Lang, Sourcefabric Head of Products, to contact you about the company side of things. Cheers! Daniel

**Comment by ghost** [comment]
Thank you Daniel :)

Cheers! Zsolt

**Pull request merged**
