### PR TITLE
Bring snapshots up to date with current packaging

### PR DESCRIPTION
**Pull request by danielhjames**
Since packaging scripts were moved to their own repo, the snapshot version of the package has not kept current.  This pull request brings packaging files back into sync.

### CODE REVIEW

**Comment by asantoni** [comment]
I thought the debian directory was not supposed to be in your source distribution. Can we pull it out into your packaging repo?

**Comment by danielhjames** [comment]
That would be a better alternative, please delete the debian/ directory and the file gen-snapshot.sh instead of merging this. I can take care of fixing up the snapshots server.

**Comment by asantoni** [comment]
OK, will do, thanks Daniel!

**Comment by asantoni** [comment]
Done and pushed to 2.5.x.

**Comment by danielhjames** [comment]
Thanks, snapshot script has been fixed.

**Pull request closed without merging**
