### PR TITLE
CC-5481 Support for upload of MP2 encoded files

### PR DESCRIPTION
**Pull request by danielhjames**
Two small changes enable MPEG-1 Layer 2 (.mp2) files to be uploaded and organized by media-monitor. Scheduling and playout via Liquidsoap already works. There is also a patch to mutagen so that it returns the mime type of audio/mp2 to the Airtime database. Audition of MP2 files does not work in HTML5 audio, so the Airtime Library displays the padlock icon for this mime type.

Patching Mutagen has required unpacking the virtualenv pybundle and re-compressing it, which accounts for almost all the new files in this pull request. For reference, there is also a patch file showing this change. Two obsolete patches have been moved out of the way.

### CODE REVIEW

**Comment by asantoni** [comment]
Hi Daniel, thanks for being diligent about testing this stuff and checking it thoroughly. I'd prefer to wait until there's a solution for the remaining jplayer issue you mentioned before merging this. Thanks!

**Comment by asantoni** [comment]
So is this done and ready for review? What works and what doesn't?

**Comment by danielhjames** [comment]
An improved patch is available at: http://code.google.com/p/mutagen/issues/detail?id=163#c1
against the latest Mutagen 1.2.2. We currently bundle version 1.2.1 so if you want me to update this and include the patch, please let me know.

**Comment by danielhjames** [comment]
Hi Albert, I have updated Mutagen to 1.22 and included the upstream patch for MP2 support. The main improvement of the upstream patch is that MP2 files which have been tagged with ID3 metadata can now have that metadata read by media-monitor. This pull request is ready for review.

**Comment by danielhjames** [comment]
No longer valid, we do not use the pybundle with the new installer

**Pull request closed without merging**
